### PR TITLE
Better controls for ramp

### LINKED ISSUE #181: Add button to disable sweep temporarily
Useful for example when observing a beatnote on a spectrum analyzer. Right now you have to disconnect the sweep signal cable.

### LINKED ISSUE #193: Use range slider for ramp
Would be more intuitive and simple compared to sliders and buttons for ramp amplitude and ramp position.

Range sliders are implemented by [superqt](https://github.com/napari/superqt/blob/main/docs/sliders.md#range-slider).

### PR DESCRIPTION
**Pull request by bleykauf**
I think the controls for setting the ramps were somewhat clunky so I implemented both center and ramp amplitude as a range slider. This adds [superqt](https://github.com/napari/superqt) as a dependency. Currently, the GUI looks like this:

new_ui

Note that it is also possible to drag the range around which I think is pretty neat :) I also added some flake8 warnings that were clashing with black (and are not pep8 compatible anyway) and cleaned up some things in `main_window.py`.

@hermitdemschoenenleben: What do you think?

There are still two open questions/issues:
* I am not sure if there is a better way of adding QRangeSlider than via an extra file in `gui/ui`. I promoted a `QSlider` to `QRangeSlider` in Qt Creator and added the file with `.h` file extension as the header.
* I removed `param2ui` which was previously handling the amplitude slider since it would now need `self.parameters.center.value` but I cannot pass `self`. Any ideas?

There are some other things I would like to include in this PR:
- [x] Add a Start/Stop button for the ramp. Will close #181.
- [x] Set defaults for the range slider and update the displayed ramp range upon start
- [x] Add a possibility to manually edit the ramp range and/or center via an input field. This could replace the current display
- [x] ~~Re-add Add the possibility to use the keyboard to change the range turn ramp on/off.~~ Doesn't make too much sense actually. Space can be used for on/off if the button is highlighted.

Any other ideas?

Closes #193 .

### CODE REVIEW

**Comment by bleykauf** [comment]
[QLabeledRangeSlider](https://github.com/napari/superqt/blob/main/docs/sliders.md#range-slider) would look even nicer I think. But QSliders only accept integers and not float values as far as I know.

**Comment by hermitdemschoenenleben** [comment]
> @hermitdemschoenenleben: What do you think?

it's great :) Way more intuitive than the old approach!

**Comment by bleykauf** [comment]
So there is actually a `QLabeledDoubleRangeSlider` which would do exactly what I want. The labels are also editable by the user so they can be used to fine tune the range.

However, there is an issue: I cannot seem the find the widget by its name, i.e. when I call it with `self.ids.ramp_slider` it returns `None`. This is only the case with the labeled version of the sliders, e.g. `QDoubleRangeSlider` works fine. The widget is displayed and works as expected but I cannot use it for anything. Any ideas?

**Comment by bleykauf** [comment]
Closed, see #228.

Features from this PR not included in #228 will be added in separate PRs.

**Pull request closed without merging**
